feat: #12 회원가입 페이지 구현
HUSTLE-UMC/HUSTLE_web pull request #24
Opened 2023-07-17 18:30 UTC by dhdh2040

## 📌 관련 이슈
> 회원가입 화면 퍼블리싱

## ✨ PR Checklist
- [x] 회원가입 페이지 생성
- [ ] 스타일 컴포넌트 적용
- [x] 비밀번호 유효성 검사 적용

## 📸 핵심 변동사항(사진은 선택)
![image](https://github.com/HUSTLE-UMC/HUSTLE_web/assets/83562727/4de33af7-8d04-4813-a425-86feaaa789bc)

## 📚 리뷰어 유의사항
체크박스와 비밀번호 일치 체크는 빠르게 추가 예정입니다.

2023-07-17 18:42 UTC, WonJuneKim requested changes
고생하셨습니다~ 추가 수정 후 다시 pr부탁드리겠습니다! 😄 👍

2023-07-17 18:42 UTC, WonJuneKim commented on hustle_web/src/pages/signIn/Information.tsx
style 컴포넌트 import 하실 때 축약어로 해주시고 import * as C 이런식으로, 호출할 때도 C.content1 이런식으로 바꿔주시면 좋을거같아요!
스타일 네이밍도 Content1 ,2 보다 어떤 컨텐트인지, input인지 알 수 있게 네이밍 바꿔주시면 좋을거같아요.

2023-07-17 18:42 UTC, WonJuneKim commented on hustle_web/src/pages/signIn/index.tsx
useState 사용중이신데 recoil 이용해서 상태선언 하는 useRecoilState로 변환 부탁드립니다!

2023-07-17 18:42 UTC, WonJuneKim commented on hustle_web/src/pages/signIn/styles.tsx
px로 되어있는 단위는 오늘 회의후에 전체 화면 조정 완료 후 반응형 단위로 교체하는 걸로 할게요!

2023-07-17 18:42 UTC, WonJuneKim commented on hustle_web/src/pages/signIn/Information.tsx
> +
유효성 검사하는 메소드는 utils 디렉토리에 하나로 모아둘게요! 삼항 연산자 조건식은 아마 권장하지 않는 방법이긴 한데 이 부분은 추후에 수정하는 걸로 하겠습니다!

2023-07-17 18:42 UTC, WonJuneKim commented on hustle_web/src/pages/signIn/Information.tsx
> +
에러 메시지나 추가 스타일 관련도 styles.ts에 묶어서 호출하는 걸로 하겠습니다.

2023-07-18 06:33 UTC, WonJuneKim reviewed
파일 디렉토리 pages, component 안에 있는거 대문자 시작으로 맞춰주시고 머지하시면 됩니다~

2023-07-18 06:33 UTC, WonJuneKim commented on hustle_web/src/pages/signIn/Information.tsx
> +import {WarningMessage, Content_1, Content_2, SigninContainer, Title, TitleContainer, ProfileImg, ProfileText, ImportantText, InputTitle, ProfileContainer, NameContainer, StyledInput, NameField, Birt
import * as P(예시) from './styles'; 로 선언하고 return 부분에 <P.Title></P.Title> 이런식으로 선언해주세요! 
Content_1 , Content_2 가 어떤 컨텐트인지 명시해주세요!

2023-07-18 09:24 UTC, Yeonsu00-12 reviewed
1.유효성 검사하는거 만들때 필요로하는 요소들 FormRequirements 이쪽에 작성하신다음에 가져다가 쓰시면 되고 디폴드 값으로 지정해놔야될 것 들은 defaultFormOption 이쪽에 작성하셔서 적용해주시면 됩니다.
2. 현재 비밀번호만 유효성 검사하게 해놓으셨는데 pattern 속성으로 "/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]+$/," 이거 지정하시면 따로 utitlity에 함수 만드신 것보다 간단하게 가능합니다. 
3. interface도 마찬가지로 파일 따로 만들었으니 작성해서 사용하시면 됩니다. 
전부 constants 파일 가시면 보실 수 있고 폼 만드시는거 잘 모르겠으면 components->Community->Question -> QuestionForm.tsx 파일 보시면 도움되실거예요. 모르시는거 있으면 물어봐주셔도 됩니다.

2023-07-26 15:24 UTC, WonJuneKim approved these changes

2023-07-28 19:07 UTC, WonJuneKim approved these changes

2023-07-28 19:40 UTC, closed without merging